# Generated by Django 3.0.2 on 2020-04-24 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='games/')),
                ('review_int', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_str', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.CharField(max_length=122, null=True)),
                ('about', models.TextField(blank=True)),
                ('platform', models.CharField(max_length=250, null=True)),
                ('developer', models.CharField(max_length=120, null=True)),
                ('publisher', models.CharField(max_length=110, null=True)),
                ('sys_requirement', models.TextField(null=True)),
            ],
        ),
    ]
